apiVersion: apps/v1
kind: Deployment
metadata:
  name: apigeeproxy
spec:
  selector:
    matchLabels:
      app: apigeeproxy
  template:
    metadata:
      labels:
        app: apigeeproxy
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - name: server
        image: eu.gcr.io/bruno-1407a/apigeeproxy:latest
        imagePullPolicy: Always
        ports:
          - name: http
            containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: target
          value: 'https://apigee-runtime-bruno-1407a-test1-7b27cf7:8443'
---
apiVersion: v1
kind: Service
metadata:
  name: apigeeservice
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: apigeeproxy
  type: NodePort
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: apigeehybrid-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: apigeehybrid-ip  
spec:
  backend:
    serviceName: apigeeservice
    servicePort: 8080  